### ISSUE TITLE
Fix horizontal scrollbar issue on Lanebook Next

### ISSUE THREAD

**Issue by jerrac** [LaneCommunityCollege/megamenu#66]
It looks like the .lmm-grouping-label label is to blame for the horizontal scrollbar always showing on Lanebook Next.

If I add:
```css
.lmm-grouping-label {
  width: 34px;
}
```
To my themes css, the horizontal scrollbar goes away.

I'm fine with leaving the fix in there, but feel free to do something better here if you want.
